---
# vars file for roles/nginxBuild
tmp: '/tmp/nginx'

tmp_conf:
  conf: '{{ tmp }}/conf'
  certs: '{{ tmp }}/certs'
  confd: '{{ tmp }}/conf.d'

templateFiles:
  dev:
    conf:
      - { src: '{{ nginx.conf.files.docker }}', dest: '{{ tmp }}' }
      - { src: 'sample_console.conf', dest: '{{ tmp_conf.confd }}' }
      - { src: '{{ nginx.conf.files.conf }}', dest: '{{ tmp_conf.confd }}' }
  prod:
    conf:
      - { src: '{{ nginx.conf.files.docker }}', dest: '{{ tmp }}' }
      - { src: '{{ nginx.conf.files.conf }}', dest: '{{ tmp_conf.confd }}' }

files:
  dev:
    conf:
      - { src: 'nginx.conf', dest: '{{ tmp_conf.conf }}' }
      - { src: 'sample_{{ env_variable }}.conf', dest: '{{ tmp_conf.confd }}' }
    certs:
      - { src: '{{ nginx.cert.files.ca }}', dest: '{{ tmp_conf.certs }}' }
      - { src: '{{ nginx.cert.files.crt }}', dest: '{{ tmp_conf.certs }}' }
      - { src: '{{ nginx.cert.files.key }}', dest: '{{ tmp_conf.certs }}' }
  prod:
    conf:
      - { src: 'nginx.conf', dest: '{{ tmp_conf.conf }}' }
      - { src: 'sample_{{ env_variable }}.conf', dest: '{{ tmp_conf.confd }}' }
    certs:
      - { src: '{{ nginx.cert.files.ca }}', dest: '{{ tmp_conf.certs }}' }
      - { src: '{{ nginx.cert.files.crt }}', dest: '{{ tmp_conf.certs }}' }
      - { src: '{{ nginx.cert.files.key }}', dest: '{{ tmp_conf.certs }}' }

repo:
  name: 'my.private.dockerrepo/proxy-nginx'
  registry: 'my.private.dockerrepo'

vault:
  vault_paths:
    cert_path: 'files/myCa.pem'
    secret_pfx: 'path_to_consul_vault/sample.pfx'
    secret_properties: 'path_to_consul_vault/common.properties'
  sensitive_data:
    pfxPathFile: '{{ ansible_parent_role_paths[0] }}/files/{{ nginx.cert.files.pfx }}'
    keyPathFile: '{{ ansible_parent_role_paths[0] }}/files/{{ nginx.cert.files.key }}'
    crtPathFile: '{{ ansible_parent_role_paths[0] }}/files/{{ nginx.cert.files.crt }}'
