---
# tasks file for roles/prometheusDeploy account
- name: Get all groups onnode
  ansible.builtin.getent:
    database: group
    split: ':'
  no_log: true

- name: Creating group "{{ nodeExporter.systemAccount.name }}" with gid "{{ nodeExporter.systemAccount.gid }}" if does not exist
  become: true
  ansible.builtin.group:
    name: "{{ nodeExporter.systemAccount.name }}"
    state: present
    gid: "{{ nodeExporter.systemAccount.gid }}"
  when: nodeExporter.systemAccount.name not in getent_group

- name: Add the user "{{ nodeExporter.systemAccount.name }}" with shell "{{ nodeExporter.systemAccount.shell }}"
  become: true
  ansible.builtin.user:
    name: "{{ nodeExporter.systemAccount.name }}"
    shell: "{{ nodeExporter.systemAccount.shell }}"
    comment: "{{ nodeExporter.systemAccount.comment }}"
    uid: "{{ nodeExporter.systemAccount.uid }}"
    group: "{{ nodeExporter.systemAccount.gid }}"
    system: yes
