---
# tasks file for roles/nginxDeploy main
- name: Validate Python Interpeter
  ansible.builtin.include_role:
    name: docker
    tasks_from: interpreterValidation
  vars:
    pythonInterpreter: "python3"

- name: Validate Docker Daemon
  ansible.builtin.include_role:
    name: docker
    tasks_from: daemon

- name: Log into Artifactory
  ansible.builtin.include_role:
    name: docker
    tasks_from: login.yml

- name: Stop container in case that is running
  ansible.builtin.include_role:
    name: docker
    tasks_from: stop

- name: Prune everything (including non-dangling images)
  ansible.builtin.include_role:
    name: docker
    tasks_from: prune.yml

- name: Create necessary Directories
  ansible.builtin.include_tasks: logDirectoryCreation.yml
  tags: [ becomeUser ]

- name: Copy Logorotate configurations
  ansible.builtin.include_tasks: logrotate.yml
  tags: [ becomeUser ]

- name: Create cronjob
  ansible.builtin.include_tasks: cron.yml
  tags: [ becomeUser ]

- name: Deploy NGINX image
  ansible.builtin.include_tasks: nginxDeploy.yml

- name: Log out from Artifactory
  ansible.builtin.include_role:
    name: docker
    tasks_from: logout.yml

- name: Port Validation
  ansible.builtin.include_role:
    name: docker
    tasks_from: portValidation.yml
