---
# vars file for roles/cadvisorBuild
tmp: '/tmp/cadvisor'

tmp_conf:
  certs: '{{ tmp }}/certs'

files:
  dev:
    certs:
      - { src: '{{ cadvisor.cert.files.crt }}', dest: '{{ tmp_conf.certs }}' }
      - { src: '{{ cadvisor.cert.files.key }}', dest: '{{ tmp_conf.certs }}' }
  prod:
    certs:
      - { src: '{{ cadvisor.cert.files.crt }}', dest: '{{ tmp_conf.certs }}' }
      - { src: '{{ cadvisor.cert.files.key }}', dest: '{{ tmp_conf.certs }}' }

repo:
  name: 'my.private.dockerrepo/cadvisor'
  registry: 'my.private.dockerrepo'

vault:
  vault_paths:
    cert_path: 'files/CA.pem'
    secret_pfx: 'vault_path/sample.pfx'
    secret_properties: 'vault_path/common.properties'
  sensitive_data:
    pfxPathFile: '{{ ansible_parent_role_paths[0] }}/files/{{ cadvisor.cert.files.pfx }}'
    keyPathFile: '{{ ansible_parent_role_paths[0] }}/files/{{ cadvisor.cert.files.key }}'
    crtPathFile: '{{ ansible_parent_role_paths[0] }}/files/{{ cadvisor.cert.files.crt }}'
