---
# tasks file for roles/nginxBuild main
- name: Validate Python Interpeter
  ansible.builtin.include_role:
    name: docker
    tasks_from: interpreterValidation
  vars:
    pythonInterpreter: "python3"

- name: Block for NGINX
  block:
    - name: Get CA certificates from Vault for Prometheus
      ansible.builtin.include_role:
        name: vault

    - name: Create relevant directories
      ansible.builtin.include_role:
        name: docker
        tasks_from: prerequisites
   
    - name: Premare main NGINX conf file
      ansible.builtin.include_tasks: conf.yml

    - name: Build Dockerfile
      ansible.builtin.include_role:
        name: docker
  always:
    - name: Cleanup always at the end of previous tasks
      ansible.builtin.include_role:
        name: vault
        tasks_from: cleanUp

    - name: Cleanup dir(s)
      ansible.builtin.include_role:
        name: docker
        tasks_from: cleanUpPrerequisites
