local:
  hosts:
    localhost:

proxy_prod:
  hosts:
    dev1:
    dev2:

prometheusGrafanaServers:
  hosts:
    server1:
    server2:
    server3:

prometheusClients:
  hosts:
    client1:
    client2:
    client3:
