---
# tasks file for roles/prometheusDeploy account
- name: Get all groups onnode
  ansible.builtin.getent:
    database: group
    split: ':'
  no_log: true

- name: Creating system account "{{ prometheus.systemAccount.name }}" with gid "{{ prometheus.systemAccount.gid }}" if does not exist
  become: true
  ansible.builtin.group:
    name: "{{ prometheus.systemAccount.name }}"
    state: present
    gid: "{{ prometheus.systemAccount.gid }}"
  when: prometheus.systemAccount.name not in getent_group

- name: Add the user "{{ prometheus.systemAccount.name }}" with shell "{{ prometheus.systemAccount.shell }}"
  become: true
  ansible.builtin.user:
    name: "{{ prometheus.systemAccount.name }}"
    shell: "{{ prometheus.systemAccount.shell }}"
    comment: "{{ prometheus.systemAccount.comment }}"
    uid: "{{ prometheus.systemAccount.uid }}"
    group: "{{ prometheus.systemAccount.gid }}"
    system: yes
