---
# tasks file for roles/docker stop
- name: Remove Docker Container
  community.docker.docker_container:
    name: "{{ repo.container_name }}"
    state: absent
    container_default_behavior: compatibility
