---
# vars file for prometheusDeploy
portBinds:
  - '{{ prometheus.conf.port }}:{{ prometheus.conf.port }}'

portsToCheck:
  - '{{ prometheus.conf.port }}'

repo:
  name: 'my.private.dockerrepo/prometheus'
  registry: 'my.private.dockerrepo'
  container_name: 'prometheus'
